#!/usr/bin/with-contenv bash

# Make abc user a member of the audio group
sed -E -i 's/(audio\:x\:[0-9]+\:)/\1abc/g' /etc/group

# Set bash as shell for abc user
sed -E -i 's/(abc\:x\:[0-9]+\:([0-9]+)\:\:\/config\:)\/bin\/false/\1\/bin\/bash/g' /etc/passwd

# Run plexmediaplayer as abc user to avoid segfault due to chromium running as root
su -c 'plexmediaplayer --scale-factor=1' abc
